apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  labels:
    example: route
spec:
  grafana:
    enabled: true
    route: true
  prometheus:
    enabled: true
    route: true
  server:
    route: true
  dex:
    image: quay.io/ablock/dex
    openShiftOAuth: true
    version: openshift-connector
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
      g, argocd-admins, role:admin
    scopes: '[groups]'
